Repository ladybug-tools/dragonfly-core, pull requests merged in 2020-06, with the labels that each got.

#131 feat(building): Add perimeter_offset as an option on classmethods
  dragonfly/building.py
  requirements.txt
  tests/building_test.py
  tests/model_test.py
Labels: core, dragonfly, enhancement

#134 fix(deps): bump ladybug-geometry-polyskel l from 1.1.0 to 1.2.0
  dragonfly/building.py
  requirements.txt
Labels: bug, enhancement

#135 fix(polyskel): Remove use of holes for now
  dragonfly/building.py
Labels: bug

#136 fix(deps): bump honeybee-core from 1.32.0 to 1.32.1
  requirements.txt
Labels: bug, dependencies

#140 style(polyskel): Only bypass polyskel for RuntimeError
  dragonfly/building.py
Labels: enhancement

#145 tests(geojson): Add sample of a minimal geoJSON for testing
  tests/geojson/TestGeoJSON_minimal.geojson
Labels: documentation

#153 fix(room2d): Fix bug in returned adjacency info
  dragonfly/room2d.py
Labels: bug

#154 Add plenum zones to Room2D.to_honeybee() method
  dragonfly/room2d.py
  tests/room2d_test.py
Labels: critical

#158 feat(story): Add floor_height property to Story
  dragonfly/building.py
  dragonfly/model.py
  dragonfly/room2d.py
  dragonfly/story.py
  tests/model_test.py
  tests/room2d_test.py
  tests/story_test.py
Labels: bug, enhancement
